### ISSUE TITLE
Run with my data

### ISSUE THREAD

**Issue by Jae-Seung-Jeon** [enginBozkurt/LidarObstacleDetection#2]
Hello Engin Bozkurt!
My data has noise due to calibration using 3 VLP16 Lidars.
So, the ground comes out uneven and is recognized as an object like this picture.
Should I adjust variables such as minSize or distanceTol?
If so, can you tell me which file to adjust?
![Screenshot from 2020-09-22 23-07-49](https://user-images.githubusercontent.com/68648280/93893363-83348d80-fd28-11ea-98f5-c200d0a2294a.png)
![Screenshot from 2020-09-22 23-08-12](https://user-images.githubusercontent.com/68648280/93893376-862f7e00-fd28-11ea-817c-f752e1cc9c8e.png)

**Comment by enginBozkurt** [comment]
Hello Jae-Seung-Jeon;
For sparse lidar scans, you should use different clustering algorithms. Euclidean clustering is not best choice for Velodyne 16 beam lidars.
