### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by Surajj4837-th** [enginBozkurt/LidarObstacleDetection#3]
I tried running this project in Ubuntu 20.04, the screen is completely filled with PCL errors. Have you tried running the project in Ubuntu 20.04? Are there any more steps of configuration?

**Comment by ammaryasirnaich** [comment]
Hi Bozkurt, I am also facing the same issue in Ubuntu 20.04 while compiling the code! I hope you can give us any suggestion to solve it. Thanks

**Comment by lucabonamini** [comment]
Just change `add_definitions(-std=c++11)` with `add_definitions(-std=c++14)`.

**Comment by haider8645** [comment]
PCL expects now C++14 as default so the above comments by lucabonamini solves it.
